version: '3.8'

services:
  law-assistant:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    restart: unless-stopped